# Generated by Django 4.1.3 on 2022-11-19 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patientUserName',
            field=models.CharField(default='nope', max_length=30),
        ),
    ]
