# Generated by Django 4.1.3 on 2022-11-19 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_patient_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='doctor',
        ),
    ]
