# Generated by Django 4.1.3 on 2022-11-30 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_bpreadings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bpreadings',
            old_name='patient',
            new_name='patient_id',
        ),
    ]
